#!/usr/bin/env bash
# Run every GoogleTest suite under compute-sanitizer.
#
#   ./scripts/sanitize.sh                 # memcheck + racecheck + initcheck, every suite
#   ./scripts/sanitize.sh test_mc_pricing # one suite
#   TOOLS="memcheck racecheck synccheck" ./scripts/sanitize.sh
#   GTEST_FILTER='-*ProductionScale*' ./scripts/sanitize.sh
#
# racecheck is the one this repo has most reason to run: it detects races on
# __shared__ memory, which is exactly the class of bug that made 07-montecarlo
# 817 standard errors wrong at 100M paths while passing at 4M. memcheck finds
# out-of-bounds global/shared access and leaks.
#
# Instrumentation is heavy -- expect 10-100x slowdowns, more for the suites that
# run production-scale regression tests. Each run is bounded by TIMEOUT so a
# failure to attach is reported as a failure instead of hanging forever.
#
# Written for Linux (Colab included). On Windows the sanitizer failed to attach
# to any process at all unelevated -- see scripts/sanitize.ps1.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="${BIN:-$ROOT/build/bin}"
OUT="${OUT:-$ROOT/sanitizer}"
# initcheck: device memory read before anything wrote it -- a KV page or a
# workspace buffer consumed before its first fill.
TOOLS="${TOOLS:-memcheck racecheck initcheck}"
TIMEOUT="${TIMEOUT:-3600}"

CS="$(command -v compute-sanitizer || true)"
if [[ -z "$CS" && -x /usr/local/cuda/bin/compute-sanitizer ]]; then
    CS=/usr/local/cuda/bin/compute-sanitizer
fi
if [[ -z "$CS" ]]; then
    echo "compute-sanitizer not found (expected on PATH or in /usr/local/cuda/bin)" >&2
    exit 2
fi

if [[ $# -gt 0 ]]; then
    targets=("$@")
else
    mapfile -t targets < <(cd "$BIN" && ls test_* 2>/dev/null | grep -v '\.exe$' | sort)
fi
if [[ ${#targets[@]} -eq 0 ]]; then
    echo "no test_* binaries in $BIN -- build first" >&2
    exit 2
fi

mkdir -p "$OUT"
"$CS" --version | head -3

declare -a rows
failures=0

for t in "${targets[@]}"; do
    for tool in $TOOLS; do
        log="$OUT/${t}.${tool}.log"
        args=(--tool "$tool" --error-exitcode 99)
        # Leaks are only meaningful for memcheck.
        [[ "$tool" == memcheck ]] && args+=(--leak-check full)

        gtest_args=()
        [[ -n "${GTEST_FILTER:-}" ]] && gtest_args+=("--gtest_filter=$GTEST_FILTER")

        printf '%-28s %-10s ... ' "$t" "$tool"
        start=$(date +%s)
        timeout "$TIMEOUT" "$CS" "${args[@]}" "$BIN/$t" "${gtest_args[@]}" >"$log" 2>&1
        code=$?
        secs=$(( $(date +%s) - start ))

        # The exit code alone is not enough: 99 is a sanitizer finding, 124 is
        # the timeout, and anything else nonzero is a test failing on its own.
        # Also scrape the summary line, because a crash can end the run before
        # the sanitizer prints one.
        errors=$(grep -Eo 'ERROR SUMMARY: [0-9]+' "$log" | grep -Eo '[0-9]+' | tail -1)
        if grep -q "No attachable process found" "$log"; then
            status="NO-ATTACH"
        elif [[ $code -eq 124 ]]; then
            status="TIMEOUT"
        elif [[ $code -eq 99 ]]; then
            status="FINDINGS"
        elif [[ $code -ne 0 ]]; then
            status="TEST-FAIL"
        else
            status="CLEAN"
        fi
        [[ "$status" != CLEAN ]] && failures=$((failures + 1))
        printf '%-10s %5ss  errors=%s\n' "$status" "$secs" "${errors:-?}"
        rows+=("| \`$t\` | $tool | $status | ${errors:-?} | ${secs}s |")
    done
done

{
    echo "# compute-sanitizer results"
    echo
    echo "GPU: $(nvidia-smi --query-gpu=name,driver_version --format=csv,noheader 2>/dev/null || echo unknown)"
    echo
    echo "Generated by \`scripts/sanitize.sh\` on $(date -u +%Y-%m-%dT%H:%MZ)."
    echo
    echo "| suite | tool | status | errors | time |"
    echo "|---|---|---|---|---|"
    printf '%s\n' "${rows[@]}"
} >"$OUT/SUMMARY.md"

echo
echo "summary: $OUT/SUMMARY.md   logs: $OUT/"
if [[ $failures -gt 0 ]]; then
    echo "$failures run(s) were not clean"
    exit 1
fi
echo "all clean"
