# Run every GoogleTest suite under compute-sanitizer (Windows).
#
#   .\scripts\sanitize.ps1                         # memcheck + racecheck
#   .\scripts\sanitize.ps1 -Target test_mc_pricing
#   .\scripts\sanitize.ps1 -Tools memcheck -TimeoutSec 600
#
# On the GTX 1650 laptop this repo was written on, compute-sanitizer 2026.3
# failed to attach to ANY process when run unelevated -- including a 20-line
# program -- printing "No attachable process found" and then waiting on the
# target forever. The same pattern as Nsight Compute on this driver, which also
# works only elevated. So every run here is bounded by -TimeoutSec, and an
# attach failure is reported as NO-ATTACH rather than as a hang.
#
# scripts/sanitize.sh is the Linux version; Colab runs it without special
# permissions.

param(
    [string]$Target = "",
    [string[]]$Tools = @("memcheck", "racecheck"),
    [int]$TimeoutSec = 3600,
    [string]$BuildDir = "build"
)

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $PSScriptRoot
$bin = Join-Path $root "$BuildDir\bin"
$out = Join-Path $root "sanitizer"
New-Item -ItemType Directory -Force $out | Out-Null

$cs = Get-ChildItem "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v*\bin\compute-sanitizer.bat" -ErrorAction SilentlyContinue |
      Sort-Object FullName -Descending | Select-Object -First 1
if (-not $cs) { Write-Error "compute-sanitizer not found"; exit 2 }

$targets = if ($Target) { @($Target) } else {
    @(Get-ChildItem $bin -Filter "test_*.exe" | Sort-Object Name | ForEach-Object { $_.BaseName })
}
if (-not $targets) { Write-Error "no test_*.exe in $bin -- build first"; exit 2 }

$rows = @()
$failures = 0
foreach ($t in $targets) {
    foreach ($tool in $Tools) {
        $log = Join-Path $out "$t.$tool.log"
        $exe = Join-Path $bin "$t.exe"
        $extra = if ($tool -eq "memcheck") { "--leak-check full" } else { "" }
        Write-Host ("{0,-28} {1,-10} ... " -f $t, $tool) -NoNewline

        $sw = [Diagnostics.Stopwatch]::StartNew()
        # Through a generated .bat: Start-Process re-quotes an argument list
        # containing embedded quotes, and cmd then silently runs nothing.
        $bat = Join-Path $out "_run.bat"
        @(
            "@echo off",
            "`"$($cs.FullName)`" --tool $tool $extra --launch-timeout 60 --error-exitcode 99 `"$exe`" > `"$log`" 2>&1",
            "exit /b %ERRORLEVEL%"
        ) | Set-Content $bat -Encoding ascii
        $p = Start-Process cmd.exe -ArgumentList "/c `"$bat`"" -PassThru -WindowStyle Hidden
        $finished = $p.WaitForExit($TimeoutSec * 1000)
        if (-not $finished) {
            # Kill the target too: after a failed attach it blocks on its first
            # CUDA call and outlives the sanitizer.
            Get-Process | Where-Object { $_.Name -in @("compute-sanitizer", $t) } |
                Stop-Process -Force -ErrorAction SilentlyContinue
            $p | Stop-Process -Force -ErrorAction SilentlyContinue
        }
        $secs = [int]$sw.Elapsed.TotalSeconds
        $text = if (Test-Path $log) { Get-Content $log -Raw } else { "" }
        $m = [regex]::Matches($text, "ERROR SUMMARY: (\d+)")
        $errors = if ($m.Count) { $m[$m.Count - 1].Groups[1].Value } else { "?" }

        $status =
            if ($text -match "No attachable process found") { "NO-ATTACH" }
            elseif (-not $finished) { "TIMEOUT" }
            elseif ($p.ExitCode -eq 99) { "FINDINGS" }
            elseif ($p.ExitCode -ne 0) { "TEST-FAIL" }
            else { "CLEAN" }
        if ($status -ne "CLEAN") { $failures++ }

        $color = if ($status -eq "CLEAN") { "Green" } else { "Red" }
        Write-Host ("{0,-10} {1,5}s  errors={2}" -f $status, $secs, $errors) -ForegroundColor $color
        $rows += "| ``$t`` | $tool | $status | $errors | ${secs}s |"

        # An attach failure is environmental, not per-suite. Every later run
        # would spend its whole launch timeout discovering the same thing.
        if ($status -eq "NO-ATTACH") {
            Write-Warning "compute-sanitizer cannot attach on this machine; stopping. Try an elevated shell, or run scripts/sanitize.sh on Linux/Colab."
            break
        }
    }
    if ($status -eq "NO-ATTACH") { break }
}

$gpu = (& nvidia-smi --query-gpu=name,driver_version --format=csv,noheader 2>$null)
@(
    "# compute-sanitizer results", "",
    "GPU: $gpu", "",
    "Generated by ``scripts/sanitize.ps1`` on $(Get-Date -Format 'yyyy-MM-ddTHH:mm').", "",
    "| suite | tool | status | errors | time |",
    "|---|---|---|---|---|"
) + $rows | Set-Content (Join-Path $out "SUMMARY.md") -Encoding utf8

Write-Host ""
Write-Host "summary: $out\SUMMARY.md"
if ($failures) { Write-Host "$failures run(s) were not clean" -ForegroundColor Red; exit 1 }
Write-Host "all clean" -ForegroundColor Green
